### ISSUE TITLE
Debug messages

### ISSUE THREAD

**Issue by riftEmber** [fictional-pancake/turbo-spork-server#5]
I think it would be helpful to have a function that logs a message only if gd.debug, instead of having to do separate if statements.

**Comment by riftEmber** [comment]
What should I call the method?

**Comment by vpzomtrrfrt** [comment]
debug() or log() maybe?

**Comment by riftEmber** [comment]
Where is gd.debug set?

**Comment by vpzomtrrfrt** [comment]
Chat handling

**Comment by riftEmber** [comment]
Should there be some indication that its a debug message if it is logged?

**Comment by vpzomtrrfrt** [comment]
Maybe, I think we should also have debug categories so you can just 
debug one thing

**Comment by riftEmber** [comment]
So someone would call the debug function and pass a category, then we would check if that category was enabled?

**Comment by vpzomtrrfrt** [comment]
Yeah, something like that

**Comment by fortninja** [comment]
So, what categories do we want and how should we toggle them?
